module.exports = {
	// TODO: Remove corePlugins for production.
	corePlugins: {
		preflight: true,
		container: false,
		accessibility: false,
		alignContent: true,
		alignItems: true,
		alignSelf: true,
		animation: false,
		appearance: true,
		backgroundAttachment: false,
		backgroundClip: false,
		backgroundColor: true,
		backgroundImage: false,
		backgroundOpacity: true,
		backgroundPosition: false,
		backgroundRepeat: false,
		backgroundSize: false,
		borderCollapse: true,
		borderColor: true,
		borderOpacity: true,
		borderRadius: true,
		borderStyle: true,
		borderWidth: true,
		boxShadow: true,
		boxSizing: false,
		clear: false,
		cursor: true,
		display: true,
		divideColor: false,
		divideOpacity: false,
		divideStyle: false,
		divideWidth: false,
		fill: true,
		flex: true,
		flexDirection: true,
		flexGrow: true,
		flexShrink: true,
		flexWrap: true,
		float: false,
		fontFamily: true,
		fontSize: true,
		fontSmoothing: true,
		fontStyle: true,
		fontVariantNumeric: true,
		fontWeight: true,
		gap: true,
		gradientColorStops: false,
		gridAutoFlow: false,
		gridColumn: false,
		gridColumnEnd: false,
		gridColumnStart: false,
		gridRow: false,
		gridRowEnd: false,
		gridRowStart: false,
		gridTemplateColumns: true,
		gridTemplateRows: true,
		height: true,
		inset: true,
		justifyContent: true,
		justifyItems: true,
		justifySelf: true,
		letterSpacing: true,
		lineHeight: true,
		listStylePosition: false,
		listStyleType: false,
		margin: true,
		maxHeight: true,
		maxWidth: true,
		minHeight: true,
		minWidth: true,
		objectFit: false,
		objectPosition: false,
		opacity: true,
		order: true,
		outline: false,
		overflow: true,
		overscrollBehavior: false,
		padding: true,
		placeContent: false,
		placeholderColor: false,
		placeholderOpacity: false,
		placeItems: false,
		placeSelf: false,
		pointerEvents: true,
		position: true,
		resize: false,
		rotate: false,
		scale: false,
		skew: false,
		space: true, // ??
		stroke: true,
		strokeWidth: false,
		tableLayout: false,
		textAlign: true,
		textColor: true,
		textDecoration: true,
		textOpacity: true,
		textTransform: true,
		transform: false,
		transformOrigin: false,
		transitionDelay: true,
		transitionDuration: true,
		transitionProperty: true,
		transitionTimingFunction: true,
		translate: false,
		userSelect: true,
		verticalAlign: true,
		visibility: false,
		whitespace: true,
		width: true,
		wordBreak: false,
		zIndex: true,
	},

	// dark: "class",
	experimental: {
		// darkModeVariant: true,
		uniformColorPalette: true,
	},
	// future: {
	// 	removeDeprecatedGapUtilities: true,
	// 	purgeLayersByDefault: true,
	// },
	purge: [
		"./src/**/*.js",
	],
	theme: {
		extend: {
			borderRadius: {
				0: "0",       //  0px
				1: "0.25rem", //  4px
				2: "0.5rem",  //  8px
				3: "0.75rem", // 12px
				4: "1rem",    // 16px
				5: "1.25rem", // 20px
				6: "1.5rem",  // 24px
			},
		},
		screens: {
			/* eslint-disable no-multi-spaces */
			sm: `${16 +  640 + 16}px`,
			md: `${24 +  768 + 24}px`,
			lg: `${24 + 1024 + 24}px`,
			xl: `${24 + (1280 + 64) + 24}px`,
			/* eslint-enable no-multi-spaces */
		},
	},
	variants: {
		typography: {},
	},
	plugins: [
		require("@tailwindcss/ui"),
	],
}
