const defaultTheme = require("tailwindcss/defaultTheme")

const limitedCorePlugins = {
	preflight: true,
	container: false,
	accessibility: false,
	alignContent: true,
	alignItems: true,
	alignSelf: true,
	animation: false,
	appearance: true,
	backgroundAttachment: false,
	backgroundClip: false,
	backgroundColor: true,
	backgroundImage: false,
	backgroundOpacity: true,
	backgroundPosition: false,
	backgroundRepeat: false,
	backgroundSize: false,
	borderCollapse: true,
	borderColor: true,
	borderOpacity: true,
	borderRadius: true,
	borderStyle: true,
	borderWidth: true,
	boxShadow: true,
	boxSizing: false,
	clear: false,
	cursor: true,
	display: true,
	divideColor: false,
	divideOpacity: false,
	divideStyle: false,
	divideWidth: false,
	fill: true,
	flex: true,
	flexDirection: true,
	flexGrow: true,
	flexShrink: true,
	flexWrap: true,
	float: false,
	fontFamily: true,
	fontSize: true,
	fontSmoothing: true,
	fontStyle: true,
	fontVariantNumeric: true,
	fontWeight: true,
	gap: true,
	gradientColorStops: false,
	gridAutoFlow: false,
	gridColumn: false,
	gridColumnEnd: false,
	gridColumnStart: false,
	gridRow: false,
	gridRowEnd: false,
	gridRowStart: false,
	gridTemplateColumns: true,
	gridTemplateRows: true,
	height: true,
	inset: true,
	justifyContent: true,
	justifyItems: true,
	justifySelf: true,
	letterSpacing: true,
	lineHeight: true,
	listStylePosition: false,
	listStyleType: false,
	margin: true,
	maxHeight: true,
	maxWidth: true,
	minHeight: true,
	minWidth: true,
	objectFit: false,
	objectPosition: false,
	opacity: true,
	order: true,
	outline: false,
	overflow: true,
	overscrollBehavior: false,
	padding: true,
	placeContent: false,
	placeholderColor: false,
	placeholderOpacity: false,
	placeItems: false,
	placeSelf: false,
	pointerEvents: true,
	position: true,
	resize: false,
	rotate: false,
	scale: false,
	skew: false,
	space: true,
	stroke: true,
	strokeWidth: false,
	tableLayout: false,
	textAlign: true,
	textColor: true,
	textDecoration: true,
	textOpacity: true,
	textTransform: true,
	transform: false,
	transformOrigin: false,
	transitionDelay: true,
	transitionDuration: true,
	transitionProperty: true,
	transitionTimingFunction: true,
	translate: false,
	userSelect: true,
	verticalAlign: true,
	visibility: false,
	whitespace: true,
	width: true,
	wordBreak: false,
	zIndex: true,
}

module.exports = {
	corePlugins: limitedCorePlugins,

	// dark: "class",
	experimental: {
		// darkModeVariant: true,
		uniformColorPalette: true,
	},
	future: {
		// removeDeprecatedGapUtilities: true,
		// purgeLayersByDefault: true,
	},
	purge: ["./src/**/*.js"],
	theme: {
		extend: {
			borderRadius: {
				0: "0",
				1: `${1 * 0.25}rem`,
				2: `${2 * 0.25}rem`,
				3: `${3 * 0.25}rem`,
				4: `${4 * 0.25}rem`,
				5: `${5 * 0.25}rem`,
				6: `${6 * 0.25}rem`,
			},
			boxShadow: {
				"px": defaultTheme.boxShadow.xs,
				"1": defaultTheme.boxShadow.sm,
				"2": defaultTheme.boxShadow.default,
				"3": defaultTheme.boxShadow.md,
				"4": defaultTheme.boxShadow.lg,
				"5": defaultTheme.boxShadow.xl,
				"6": defaultTheme.boxShadow["2xl"],
				"px-1": defaultTheme.boxShadow.xs + ", " + defaultTheme.boxShadow.sm,
				"px-2": defaultTheme.boxShadow.xs + ", " + defaultTheme.boxShadow.default,
				"px-3": defaultTheme.boxShadow.xs + ", " + defaultTheme.boxShadow.md,
				"px-4": defaultTheme.boxShadow.xs + ", " + defaultTheme.boxShadow.lg,
				"px-5": defaultTheme.boxShadow.xs + ", " + defaultTheme.boxShadow.xl,
				"px-6": defaultTheme.boxShadow.xs + ", " + defaultTheme.boxShadow["2xl"],
			},
			fontFamily: {
				display: [
					"InterDisplay",
					...defaultTheme.fontFamily.sans,
				],
				sans: [
					...defaultTheme.fontFamily.sans.slice(1, 3),
					"Inter",
					...defaultTheme.fontFamily.sans[0], // system-ui
					...defaultTheme.fontFamily.sans.slice(3),
				],
			},
			opacity: {
				0: "0",
				5: "0.5",
				10: "0.10",
				15: "0.15",
				20: "0.20",
				25: "0.25",
				75: "0.75",
				80: "0.80",
				85: "0.85",
				90: "0.90",
				95: "0.95",
				100: "1",
			},
		},
		screens: {
			sm: `${16 + 640 + 16}px`,
			md: `${24 + 768 + 24}px`,
			lg: `${24 + 1024 + 24}px`,
			xl: `${24 + (1280 + 64) + 24}px`,
		},
	},
	variants: {},
	plugins: [require("@tailwindcss/ui")],
}
