import Head from "next/head"

const meta = {
	title: "Feather – Simply beautiful open source icons",
	description: "Feather is a collection of simply beautiful open source icons. Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency and readability.",

	// TODO: Change to "https://feathericons.com" for
	// production.
	url: process.env.NODE_ENV !== "production" ? "http://localhost:3000" : "https://feathericons.dev",
}

export default function SEO() {
	return (
		<Head>

			<meta
				charSet="utf-8"
			/>
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1"
			/>
			<link
				// TODO: See favicon-16x16.png and favicon-32x32.png.
				rel="icon"
				href={`${meta.url}/images/favicon.ico`}
			/>

			{/* Core */}
			<title>
				{meta.title}
			</title>
			<meta
				name="title"
				content={meta.title}
			/>
			<meta
				name="description"
				content={meta.description}
			/>

			{/* Facebook */}
			<meta
				property="og:type"
				content="website"
			/>
			<meta
				property="og:url"
				content={meta.url}
			/>
			<meta
				property="og:title"
				content={meta.title}
			/>
			<meta
				property="og:description"
				content={meta.description}
			/>
			<meta
				property="og:image"
				content={`https://${meta.url}/images/share.png`}
			/>

			{/* Twitter */}
			<meta
				property="twitter:card"
				content="summary_large_image"
			/>
			<meta
				property="twitter:url"
				content={meta.url}
			/>
			<meta
				property="twitter:title"
				content={meta.title}
			/>
			<meta
				property="twitter:description"
				content={meta.description}
			/>
			<meta
				property="twitter:image"
				content={`https://${meta.url}/images/share.png`}
			/>

			{/* NOTE: <meta name="twitter:creator" ...> is not
			generated by https://metatags.io but was present. */}
			<meta
				name="twitter:creator"
				content="@colebemis"
			/>

		</Head>
	)
}
